FROM nginx:1.11

ENV TZ=Asia/Shanghai
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
#COPY ./conf.d /etc/nginx/conf.d
#RUN mkdir -p /etc/letsencrypt/archive/myeushop.com
#
#COPY ./myeushop.com/fullchain1.pem /etc/letsencrypt/archive/myeushop.com
#COPY ./myeushop.com/privkey1.pem /etc/letsencrypt/archive/myeushop.com
